language: perl
perl:
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"

before_install:
  cpanm -n Devel::Cover::Report::Coveralls XML::OPML::SimpleGen
script:
  perl Build.PL && ./Build build && cover -test -report coveralls
